dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test --keepdb
deploy:
  provider: heroku
  app: ejercicio-0-dansangar2
  strategy: git
  api_key:
    secure: RtTKlyNiT66NeJM2axcTWFyaOTYPOaeDuPqWrP65aeMiiK78xwOLeEEkcF2UbxmPz4F79MPuLerELsNVNRAqyMElFzQsMJset6gfB+KJ9QrNk7K4sE+rPwn9zHZgKMe3K32PcZMafZeUKWQu9OsiGrJbr7Hy11XGXaBPT9K9jA7xm98lAYJY4dFS+lYLRA9ROJwk5/fpBMna9BLZ9OY/g5w6LLZp09XM4RXb4L4v5WeSUcnLc8v7S/AMzDJI+NrrOGT0VChtg8Y6/DGr4ACILL3hL1Lyo6f0QioeY4a3qTTpiry+uDu7mNszh/YL9FC/zOv4HwZ/pEG+ATZfp1oZaPIUQv8KQnGL4WyFMDOT3f9Ehu7CbjJqfkczh9UHV2NNbMUd16ZPedIlh26LqaZ35A4RceAQaDL0s/XJd7qyJFkzkf1hIkBQxGVc/3E7L9hEvOIa8jAIhlfzsx/eAuiTgDB6DPCP7IrGUlDTGNuo00URyYU5vkI3JtfgWEnq23xXFnCAgUMyYegw7RhyzxDYY7igFITW+pYz2QVr1BAOyC6Lni5aRoJuNCzKCvikBYPJON+5uG/+QuQCVFAiFSWZGzVHVpNaZEJDwl4fobXmB3staHXts2nAEy8BpTVHPTy2zVc0hIb+GjCJkjWduH7+dGsXMvmjPYkyhEuqK+Im6kI=
